### ISSUE TITLE
Add middlewares for working with popular database drivers

### ISSUE THREAD

**Issue by egorsmkv** [iris-contrib/middleware#11]
Ex:

- https://github.com/go-sql-driver/mysql
- https://labix.org/mgo

**Comment by kataras** [comment]
I have explained that Iris will not provide anything more that it's now, we have already rich and unique features  that no other frameworks has built'n. 

But anyone is free to make a third-party library for Iris, I cannot do all these alone forever, community must help if want to have more features, just build them and share with us :)

**Comment by kataras** [comment]
I have explained that Iris will not provide anything more that it's now (especially a GORM, use your favourite, iris will not block you, I write it on book also ). Iris has ,already, rich and unique features that no other framework has.

However anybody can make a third-party library for Iris and share with us, community must help if want to have more features,  I cannot, and I don't want to do all these alone forever, community has to be involved, this is an open source project, not a project owns & used only by me...

An Iris middleware is just a ` func(ctx *iris.Context){ /* code*/ ctx.Next() })` 
Read more at the [book](http://iris-go.com)

Thanks!!

**Comment by kataras** [comment]
I have explained that Iris will not be transform to a big and heavy framework, we keep simplicity because it's productive,  (especially a GORM, use your favourite, iris will not block you, I write it on book also ). Iris has ,already, rich and unique features that no other framework has.

However anybody can make a third-party library for Iris and share with us, community must help if want to have more features,  I cannot, and I don't want to do all these alone forever, community has to be involved, this is an open source project, not a project owns & used only by me...

An Iris middleware is just a ` func(ctx *iris.Context){ /* code*/ ctx.Next() })` 
Read more at the [book](http://iris-go.com)

Thanks!!
