### ISSUE TITLE
 app.AllowMethods undefined (type *iris.Application has no field or method AllowMethods)

### ISSUE THREAD

**Issue by kingname** [iris-contrib/middleware#39]
Code in your CORS module.

In your `example` of cors, there is a line:

```
v1 := app.Party("/api/v1", crs).AllowMethods(iris.MethodOptions) 
```

however, the `AllowMethods` is not exists.

Also, in your `cors_test.go`, `app.AllowMethods` is also invalid.

**Comment by kataras** [comment]
`AllowMethods` does exist otherwise the travis build would never passed :P Look more at: https://travis-ci.org/iris-contrib/middleware.

@kingname please try to [star/watch the Iris repo](https://github.com/kataras/iris/stargazers) in order to be always up-to-date , each version has its own HISTORY.md entry so you never miss the important things. To upgrade your local Iris execute the following command in your shell:  `go get -u github.com/kataras/iris`. Have fun!
